In [1]:
# import module
import numpy as np

In [3]:
# single dimensional array
# list
my_list = [1, 2, 3, 4]

# convert into array using numpy arrays
x = np.array(my_list)

# print array
print(x)

[1 2 3 4]


In [8]:
# multidimansional array
ma = np.array([[12,334, 5, 5], [7, 6, 4, 8],[1,2,3,4]])

#print(ma)
ma

array([[ 12, 334,   5,   5],
       [  7,   6,   4,   8],
       [  1,   2,   3,   4]])

In [10]:
# create transpose
ma.T

array([[ 12,   7,   1],
       [334,   6,   2],
       [  5,   4,   3],
       [  5,   8,   4]])